# Generated by Django 3.2.5 on 2021-09-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
