# Generated by Django 3.2.5 on 2021-09-20 00:25

import concurrency.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_alter_appointment_time_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='version',
            field=concurrency.fields.IntegerVersionField(default=0, help_text='record revision number'),
        ),
    ]
