# Generated by Django 3.2.5 on 2021-09-20 01:17

import concurrency.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_remove_appointment_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='version',
            field=concurrency.fields.IntegerVersionField(default=0, help_text='record revision number'),
        ),
    ]
