# Generated by Django 3.2.5 on 2021-09-20 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_appointment_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='version',
        ),
      
    ]
