# Generated by Django 3.2.5 on 2021-10-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_auto_20211008_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='c_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='u_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
