# Generated by Django 3.2.5 on 2021-10-08 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_auto_20211008_2037'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set(),
        ),
    ]
