# Generated by Django 3.2.5 on 2021-10-08 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0010_alter_course_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set(),
        ),
    ]
