# Generated by Django 3.2.5 on 2021-10-11 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_auto_20211011_0939'),
        ('teacher', '0011_alter_course_unique_together'),
    ]

    operations = [
    ]
