# Generated by Django 3.2.5 on 2021-08-28 08:43

from django.db import migrations, models
import django.db.models.deletion
import login.models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
        ('login', '0002_auto_20210828_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.course'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, default=login.models.get_default_profile_image, max_length=255, null=True, upload_to=login.models.get_profile_image_filepath),
        ),
    ]
