# Generated by Django 3.2.5 on 2021-11-04 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0012_merge_20211011_1348'),
        ('login', '0009_auto_20211104_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='course',
            field=models.ManyToManyField(default='select', to='teacher.course'),
        ),
    ]
